/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ResourceBundle;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.HelpSetException;
import javax.swing.JOptionPane;
import source.Configuration;

/**
 *
 * @author Andres LLamosas
 */
public class AjustesAvanzados extends javax.swing.JDialog {

    String old;

    /**
     * Creates new form AjustesAvanzados
     */
    public AjustesAvanzados() {
        initComponents();
        cargarDatos();
        this.lblPuertoIncorrecto.setVisible(false);
        getRootPane().setDefaultButton(this.btnAceptar);
        old = txtPuerto.getText();
        javaHelp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtPuerto = new javax.swing.JTextField();
        lblPuertoIncorrecto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        chkPreguntarAlSalir = new javax.swing.JCheckBox();
        chkPenalizar = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTiempoEspera = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIntentos = new javax.swing.JTextField();
        chkStartup = new javax.swing.JCheckBox();

        jTextField1.setText("jTextField1");

        setModal(true);
        setResizable(false);
        setSize(new java.awt.Dimension(227, 122));
        setType(java.awt.Window.Type.POPUP);

        lblPuertoIncorrecto.setForeground(new java.awt.Color(206, 59, 41));
        lblPuertoIncorrecto.setText(ResourceBundle.getBundle("messages.messages").getString("PUERTO_INCORRECTO"));

        jLabel1.setText(ResourceBundle.getBundle("messages.messages").getString("PUERTO"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPuertoIncorrecto)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPuertoIncorrecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPuerto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancelar.setText(ResourceBundle.getBundle("messages.messages").getString("CANCELAR"));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceptar.setText(ResourceBundle.getBundle("messages.messages").getString("ACEPTAR"));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        chkPreguntarAlSalir.setText(ResourceBundle.getBundle("messages.messages").getString("MINIMIZAR_AL_SALIR"));

        chkPenalizar.setText(ResourceBundle.getBundle("messages.messages").getString("PENALIZAR_CONTRASENA"));
        chkPenalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPenalizarActionPerformed(evt);
            }
        });

        jLabel3.setText(ResourceBundle.getBundle("messages.messages").getString("TIEMPO_VOLVER_INTENTAR"));

        jLabel2.setText(ResourceBundle.getBundle("messages.messages").getString("NUMERO_INTENTOS"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTiempoEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTiempoEspera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        chkStartup.setSelected(true);
        chkStartup.setText(ResourceBundle.getBundle("messages.messages").getString("EJECUTAR_EN_INICIO"));
        chkStartup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkStartupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkPenalizar)
                            .addComponent(chkPreguntarAlSalir)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkStartup))
                        .addContainerGap(76, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkPreguntarAlSalir)
                .addGap(18, 18, 18)
                .addComponent(chkPenalizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkStartup)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (!txtPuerto.getText().equals(old)) {
            if (validarPuerto()) {
                Configuration.crearPropCierre(chkPreguntarAlSalir.isSelected(),
                        chkStartup.isSelected());
                Configuration.crearPropPuerto(txtPuerto.getText());
                lblPuertoIncorrecto.setVisible(false);
                this.setVisible(false);
            } else {
                lblPuertoIncorrecto.setVisible(true);
            }
        } else {
            establecerAjustes();
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void chkPenalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPenalizarActionPerformed
        txtIntentos.setEnabled(chkPenalizar.isSelected());
        txtTiempoEspera.setEnabled(chkPenalizar.isSelected());
    }//GEN-LAST:event_chkPenalizarActionPerformed

    private void chkStartupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkStartupActionPerformed
        String rutaStartup = "C:\\Users\\%username%\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup";
        try {
            if(chkStartup.isSelected()) {
                String rutaApp = System.getProperty("user.dir") + "\\Neron.exe";
                String procesoLnk = "mklink \"" + rutaStartup + "\\Neron.lnk\" \"" + rutaApp + "\"";
                ProcessBuilder builder = new ProcessBuilder("cmd", "/c", procesoLnk);
                Process p = builder.start();
                int exitCode = p.waitFor();
                if(exitCode != 0) {                    
                    JOptionPane.showMessageDialog(this,
                            ResourceBundle.getBundle("messages.messages").getString("PERMISOS_INSUFICIENTES"),
                            ResourceBundle.getBundle("messages.messages").getString("NERON"), 
                            JOptionPane.ERROR_MESSAGE);
                    chkStartup.setSelected(false);
                }
            } else {            
                String procesoEliminar = "del \"" + rutaStartup + "\\Neron.lnk\"";
                ProcessBuilder builder = new ProcessBuilder("cmd", "/c", procesoEliminar);
                Process p = builder.start();
                int exitCode = p.waitFor();
                if(exitCode != 0) {                
                    System.out.println("Fallo en el proceso - " + exitCode);
                }
            }
        } catch (IOException ex) {
            source.Logger.error("AjustesAvanzados", "chkStartup()", 
                    "Excepción genérica en la creación de acceso directo", ex.getMessage());
        } catch (InterruptedException ex) {
            source.Logger.error("AjustesAvanzados", "chkStartup()", 
                    "Excepción en la creación de acceso directo", ex.getMessage());
        }
    }//GEN-LAST:event_chkStartupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjustesAvanzados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjustesAvanzados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjustesAvanzados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjustesAvanzados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JCheckBox chkPenalizar;
    private javax.swing.JCheckBox chkPreguntarAlSalir;
    private javax.swing.JCheckBox chkStartup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblPuertoIncorrecto;
    private javax.swing.JTextField txtIntentos;
    private javax.swing.JTextField txtPuerto;
    private javax.swing.JTextField txtTiempoEspera;
    // End of variables declaration//GEN-END:variables

    private void cargarDatos() {
        String puerto = Integer.toString(Configuration.getPropPuerto());
        txtPuerto.setText(puerto);
        chkPreguntarAlSalir.setSelected(Configuration.getPropCierre()[0]);
        chkStartup.setSelected(Configuration.getPropCierre()[1]);
        chkPenalizar.setSelected((boolean)Configuration.getPropPenalizacion()[0]);
        txtIntentos.setText(Integer.toString((int)Configuration.getPropPenalizacion()[1]));
        txtTiempoEspera.setText(Integer.toString((int)Configuration.getPropPenalizacion()[2]));
    }

    private void establecerAjustes() {        
        Configuration.crearPropCierre(
                chkPreguntarAlSalir.isSelected(),
                chkStartup.isSelected());
        Configuration.crearPropPenalizacion(
                new String[]{
                    Boolean.toString(chkPenalizar.isSelected()),
                    txtIntentos.getText(),
                    txtTiempoEspera.getText()}
        );
    }

    private boolean validarPuerto() {
        boolean valido = false;
        try {
            int puerto = Integer.parseInt(txtPuerto.getText());
            if (puerto >= 1024 && puerto <= 49151) {
                valido = true;
            }
        } catch (Exception ex) {
            source.Logger.error("AjustesAvanzados", "validarPuerto()", 
                    "Se ha introducido un puerto no válido", ex.getMessage());
        }
        return valido;
    }

    private void javaHelp() {
        try {
            File fichero = new File(Configuration.getJavaHelp());
            URL hsURL = fichero.toURI().toURL();            
            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            
            HelpBroker hb = helpset.createHelpBroker();
            hb.enableHelpKey(this.getContentPane(), "principal", helpset);

            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();            
            Point p = new Point((int)screenSize.getWidth()/4,(int)screenSize.getHeight()/4);
            hb.setLocation(p);
        } catch (MalformedURLException ex) {
            source.Logger.error("AjustesAvanzados", "javaHelp()", 
                    "URL mal formada", ex.getMessage());
        } catch (HelpSetException ex) {
            source.Logger.error("AjustesAvanzados", "javaHelp()", 
                    "Excepcion general", ex.getMessage());
        }
    }
}
