/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ResourceBundle;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.HelpSetException;
import javax.swing.ImageIcon;
import source.Configuration;

/**
 *
 * @author Andres LLamosas
 */
public class Idiomas extends javax.swing.JDialog {

    Opciones opciones;

    /**
     * Creates new form CambiarIdioma
     *
     * @param opciones menu opciones padre
     */
    public Idiomas(Opciones opciones) {
        initComponents();
        setTooltips();
        this.opciones = opciones;
        javaHelp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnEspanol = new javax.swing.JButton();
        btnIngles = new javax.swing.JButton();
        btnFrances = new javax.swing.JButton();
        btnRuso = new javax.swing.JButton();
        btnAleman = new javax.swing.JButton();
        btnChino = new javax.swing.JButton();
        btnItaliano = new javax.swing.JButton();
        btnTayiki = new javax.swing.JButton();
        btnZulu = new javax.swing.JButton();

        setTitle(ResourceBundle.getBundle("messages.messages").getString("IDIOMA"));
        setModal(true);
        setResizable(false);

        jLabel1.setText(ResourceBundle.getBundle("messages.messages").getString("SELECCIONA_IDIOMA"));

        btnEspanol.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andres LLamosas\\Desktop\\Neron\\Neron Server\\media\\spain.png")); // NOI18N
        btnEspanol.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEspanol.setMaximumSize(new java.awt.Dimension(40, 20));
        btnEspanol.setMinimumSize(new java.awt.Dimension(40, 20));
        btnEspanol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspanolActionPerformed(evt);
            }
        });

        btnIngles.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andres LLamosas\\Desktop\\Neron\\Neron Server\\media\\england.png")); // NOI18N
        btnIngles.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIngles.setMaximumSize(new java.awt.Dimension(40, 20));
        btnIngles.setMinimumSize(new java.awt.Dimension(40, 20));
        btnIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInglesActionPerformed(evt);
            }
        });

        btnFrances.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andres LLamosas\\Desktop\\Neron\\Neron Server\\media\\france.png")); // NOI18N
        btnFrances.setToolTipText("");
        btnFrances.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFrances.setMaximumSize(new java.awt.Dimension(40, 20));
        btnFrances.setMinimumSize(new java.awt.Dimension(40, 20));
        btnFrances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrancesActionPerformed(evt);
            }
        });

        btnRuso.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andres LLamosas\\Desktop\\Neron\\Neron Server\\media\\russia.png")); // NOI18N
        btnRuso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRuso.setMaximumSize(new java.awt.Dimension(40, 20));
        btnRuso.setMinimumSize(new java.awt.Dimension(40, 20));
        btnRuso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRusoActionPerformed(evt);
            }
        });

        btnAleman.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andres LLamosas\\Desktop\\Neron\\Neron Server\\media\\germany.png")); // NOI18N
        btnAleman.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAleman.setMaximumSize(new java.awt.Dimension(40, 20));
        btnAleman.setMinimumSize(new java.awt.Dimension(40, 20));
        btnAleman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlemanActionPerformed(evt);
            }
        });

        btnChino.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andres LLamosas\\Desktop\\Neron\\Neron Server\\media\\china.png")); // NOI18N
        btnChino.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnChino.setMaximumSize(new java.awt.Dimension(40, 20));
        btnChino.setMinimumSize(new java.awt.Dimension(40, 20));
        btnChino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChinoActionPerformed(evt);
            }
        });

        btnItaliano.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andres LLamosas\\Desktop\\Neron\\Neron Server\\media\\italy.png")); // NOI18N
        btnItaliano.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnItaliano.setMaximumSize(new java.awt.Dimension(40, 20));
        btnItaliano.setMinimumSize(new java.awt.Dimension(40, 20));
        btnItaliano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItalianoActionPerformed(evt);
            }
        });

        btnTayiki.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andres LLamosas\\Desktop\\Neron\\Neron Server\\media\\tajikistan.png")); // NOI18N
        btnTayiki.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTayiki.setMaximumSize(new java.awt.Dimension(40, 20));
        btnTayiki.setMinimumSize(new java.awt.Dimension(40, 20));
        btnTayiki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTayikiActionPerformed(evt);
            }
        });

        btnZulu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Andres LLamosas\\Desktop\\Neron\\Neron Server\\media\\kwazulu.png")); // NOI18N
        btnZulu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnZulu.setMaximumSize(new java.awt.Dimension(40, 20));
        btnZulu.setMinimumSize(new java.awt.Dimension(40, 20));
        btnZulu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZuluActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnItaliano, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(btnTayiki, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnChino, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(btnAleman, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEspanol, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(btnFrances, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnRuso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnZulu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAleman, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(btnIngles, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(btnChino, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEspanol, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(btnFrances, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(btnRuso, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnItaliano, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(btnTayiki, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(btnZulu, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChinoActionPerformed
        establecerIdioma("zh");
    }//GEN-LAST:event_btnChinoActionPerformed

    private void btnAlemanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlemanActionPerformed
        establecerIdioma("de");
    }//GEN-LAST:event_btnAlemanActionPerformed

    private void btnInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInglesActionPerformed
        establecerIdioma("en");
    }//GEN-LAST:event_btnInglesActionPerformed

    private void btnEspanolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspanolActionPerformed
        establecerIdioma("es");
    }//GEN-LAST:event_btnEspanolActionPerformed

    private void btnFrancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrancesActionPerformed
        establecerIdioma("fr");
    }//GEN-LAST:event_btnFrancesActionPerformed

    private void btnRusoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRusoActionPerformed
        establecerIdioma("ru");
    }//GEN-LAST:event_btnRusoActionPerformed

    private void btnItalianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItalianoActionPerformed
        establecerIdioma("it");
    }//GEN-LAST:event_btnItalianoActionPerformed

    private void btnTayikiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTayikiActionPerformed
        establecerIdioma("tg");
    }//GEN-LAST:event_btnTayikiActionPerformed

    private void btnZuluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZuluActionPerformed
        establecerIdioma("zu");
    }//GEN-LAST:event_btnZuluActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    System.out.println(info.getName());
                    System.out.println(info.getClassName());
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Idiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Idiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Idiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Idiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAleman;
    private javax.swing.JButton btnChino;
    private javax.swing.JButton btnEspanol;
    private javax.swing.JButton btnFrances;
    private javax.swing.JButton btnIngles;
    private javax.swing.JButton btnItaliano;
    private javax.swing.JButton btnRuso;
    private javax.swing.JButton btnTayiki;
    private javax.swing.JButton btnZulu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void setTooltips() {
        btnAleman.setToolTipText("Deustch");
        btnChino.setToolTipText("中文");
        btnFrances.setToolTipText("Français");
        btnEspanol.setToolTipText("Español");
        btnIngles.setToolTipText("English");
        btnItaliano.setToolTipText("Italiano");
        btnRuso.setToolTipText("русский");
        btnTayiki.setToolTipText("тољикистон");
        btnZulu.setToolTipText("Zulu");
        
        btnAleman.setIcon(new ImageIcon("media/germany.png"));
        btnChino.setIcon(new ImageIcon("media/china.png"));
        btnFrances.setIcon(new ImageIcon("media/france.png"));
        btnEspanol.setIcon(new ImageIcon("media/spain.png"));
        btnIngles.setIcon(new ImageIcon("media/england.png"));
        btnItaliano.setIcon(new ImageIcon("media/italy.png"));
        btnRuso.setIcon(new ImageIcon("media/russia.png"));
        btnTayiki.setIcon(new ImageIcon("media/tajikistan.png"));
        btnZulu.setIcon(new ImageIcon("media/kwazulu.png"));
    }

    private void establecerIdioma(String idioma) {
        Configuration.crearPropIdioma(idioma);
        this.setVisible(false);
        opciones.cambios = true;
    }

    private void javaHelp() {
        try {
            File fichero = new File(Configuration.getJavaHelp());
            URL hsURL = fichero.toURI().toURL();            
            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            
            HelpBroker hb = helpset.createHelpBroker();
            hb.enableHelpKey(this.getContentPane(), "principal", helpset);

            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();            
            Point p = new Point((int)screenSize.getWidth()/4,(int)screenSize.getHeight()/4);
            hb.setLocation(p);
        } catch (MalformedURLException ex) {
            source.Logger.error("Idiomas", "javaHelp()", "URL mal formada", ex.getMessage());
        } catch (HelpSetException ex) {
            source.Logger.error("Idiomas", "javaHelp()", "Excepcion general", ex.getMessage());
        }
    }
}
