/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.io.File;
import java.io.IOException;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.imageio.ImageIO;
import server.Server;
import source.Configuration;
import source.InstanceManager;
import source.LookNFeel;
import source.PassManager;
import source.TrayNotification;

/**
 *
 * @author Andres
 */
public class Login extends javax.swing.JFrame {

    PassManager pm = new PassManager();
    TrayNotification tray;
    static Server servidor;
    static MenuPrincipal menuPrincipal;

    /**
     * Creates new form MenuValidacion
     */
    public Login() {
        Locale.setDefault(new Locale(Configuration.getPropIdioma()));
        if (pm.primerInicio()) {
            PrimerInicio ec = new PrimerInicio();
            ec.setVisible(true);
        }
        initComponents();
        try {
            this.setIconImage(ImageIO.read(new File("media/square-icon.png")));
        } catch (IOException ex) {
            source.Logger.error("MenuValidacion", "MenuValidacion()", "No se ha encontrado el square-icon.png", ex.getMessage());
        }
        this.lblContrasenaIncorrecta.setVisible(false);
        this.getRootPane().setDefaultButton(this.iniciarSesion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPass = new javax.swing.JPasswordField();
        iniciarSesion = new javax.swing.JButton();
        lblNeron = new javax.swing.JLabel();
        lblContrasenaIncorrecta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(ResourceBundle.getBundle("messages.messages").getString("NERON"));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        iniciarSesion.setText(ResourceBundle.getBundle("messages.messages").getString("INICIAR_SESION"));
        iniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionActionPerformed(evt);
            }
        });

        lblNeron.setIcon(LookNFeel.getNeron());

        lblContrasenaIncorrecta.setForeground(new java.awt.Color(206, 59, 41));
        lblContrasenaIncorrecta.setText(ResourceBundle.getBundle("messages.messages").getString("CONTRASENA_INCORRECTA"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNeron)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContrasenaIncorrecta)
                    .addComponent(iniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblNeron)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblContrasenaIncorrecta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionActionPerformed
        // TODO add your handling code here:
        if (pm.validarAutenticidad(this.txtPass.getText())) {
            MenuPrincipal menuPrincipal = new MenuPrincipal(this.txtPass.getText());
            menuPrincipal.setVisible(true);
            this.setVisible(false);
            if (tray == null) {
                tray = new TrayNotification(this);
                tray.setPrincipal(menuPrincipal);
                menuPrincipal.setTray(tray);
                setMenuPrincipal(menuPrincipal);
                servidor = new Server(menuPrincipal);
                servidor.start();
            }
            this.lblContrasenaIncorrecta.setVisible(false);
            this.txtPass.setText("");
        } else {
            this.lblContrasenaIncorrecta.setVisible(true);
        }
    }//GEN-LAST:event_iniciarSesionActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (tray == null) {
            new InstanceManager().cerrarApp();
        } else {
            this.setVisible(false);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        LookNFeel.setLookAndFeel();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            if (new InstanceManager().comprobar()) {
                new Login().setVisible(true);
            } else {
                System.exit(0);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton iniciarSesion;
    private javax.swing.JLabel lblContrasenaIncorrecta;
    private javax.swing.JLabel lblNeron;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
    
    public static void reiniciarServidor(){
        servidor.stop();
        servidor = new Server(menuPrincipal);
        servidor.start();
    }

    private void setMenuPrincipal(MenuPrincipal menuPrincipal) {
        Login.menuPrincipal = menuPrincipal;        
    }
}
