/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ResourceBundle;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.HelpSetException;
import javax.swing.JOptionPane;
import source.Configuration;
import source.PassManager;
import source.TableManager;

/**
 *
 * @author Andres
 */
public class NuevaContrasena extends javax.swing.JDialog {

    TableManager tm;
    /**
     * Creates new form CambiarContrasena
     */    
    public NuevaContrasena() {
    }
    
    public NuevaContrasena(TableManager tm) {
        initComponents();
        this.setModal(true);
        this.tm = tm;
        this.getRootPane().setDefaultButton(this.btnAceptar);
        javaHelp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAnterior = new javax.swing.JLabel();
        lblNueva = new javax.swing.JLabel();
        lblRepite = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtAnterior = new javax.swing.JPasswordField();
        txtNueva = new javax.swing.JPasswordField();
        txtRepite = new javax.swing.JPasswordField();

        setAlwaysOnTop(true);
        setModal(true);
        setResizable(false);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        lblAnterior.setText(ResourceBundle.getBundle("messages.messages").getString("ANTERIOR_CONTRASENA"));

        lblNueva.setText(ResourceBundle.getBundle("messages.messages").getString("NUEVA_CONTRASENA"));

        lblRepite.setText(ResourceBundle.getBundle("messages.messages").getString("REPITE_CONTRASENA"));

        btnAceptar.setText(ResourceBundle.getBundle("messages.messages").getString("ACEPTAR"));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText(ResourceBundle.getBundle("messages.messages").getString("CANCELAR"));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtAnterior.setToolTipText(ResourceBundle.getBundle("messages.messages").getString("SEGURIDAD_MINIMA"));

        txtNueva.setToolTipText(ResourceBundle.getBundle("messages.messages").getString("SEGURIDAD_MINIMA"));

        txtRepite.setToolTipText(ResourceBundle.getBundle("messages.messages").getString("SEGURIDAD_MINIMA"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblAnterior)
                            .addComponent(lblNueva)
                            .addComponent(lblRepite)
                            .addComponent(txtAnterior)
                            .addComponent(txtNueva))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtRepite))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNueva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRepite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRepite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName(ResourceBundle.getBundle("messages.messages").getString("SALIR"));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        this.requestFocus();
    }//GEN-LAST:event_formFocusLost

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        PassManager pm = new PassManager(); 
        if (pm.validarAutenticidad(this.txtAnterior.getText())) {
            switch (pm.validarComplejidad(this.txtNueva, this.txtRepite)) {
                case -1:                    
                    JOptionPane.showMessageDialog(this,
                            ResourceBundle.getBundle("messages.messages").getString("NO_COINCIDEN"),
                            ResourceBundle.getBundle("messages.messages").getString("CONTRASENA_INCORRECTA"), JOptionPane.ERROR_MESSAGE);
                    break;
                case 0:
                    pm.establecerContrasena(txtNueva);            
                    tm.setPass(this.txtNueva.getText());
                    tm.guardarTabla();
                    this.setVisible(false);
                    break;
                case 1:
                    JOptionPane.showMessageDialog(this,
                            ResourceBundle.getBundle("messages.messages").getString("DEMASIADO_CORTA"),
                            ResourceBundle.getBundle("messages.messages").getString("CONTRASENA_INCORRECTA"), 
                            JOptionPane.ERROR_MESSAGE);
                    break;
                case 2:
                    JOptionPane.showMessageDialog(this,
                            ResourceBundle.getBundle("messages.messages").getString("ESPACIOS_EN_BLANCO"),
                            ResourceBundle.getBundle("messages.messages").getString("CONTRASENA_INCORRECTA"), 
                            JOptionPane.ERROR_MESSAGE);
                    break;
                case 3:
                    JOptionPane.showMessageDialog(this,
                            ResourceBundle.getBundle("messages.messages").getString("NO_CARACTER_ESPECIAL"),
                            ResourceBundle.getBundle("messages.messages").getString("CONTRASENA_INCORRECTA"), 
                            JOptionPane.ERROR_MESSAGE);
                    break;
                case 4:
                    JOptionPane.showMessageDialog(this,
                            ResourceBundle.getBundle("messages.messages").getString("NO_MAYUSCULA"),
                            ResourceBundle.getBundle("messages.messages").getString("CONTRASENA_INCORRECTA"), 
                            JOptionPane.ERROR_MESSAGE);
                    break;
                case 5:
                    JOptionPane.showMessageDialog(this,
                            ResourceBundle.getBundle("messages.messages").getString("NO_MINUSCULA"),
                            ResourceBundle.getBundle("messages.messages").getString("CONTRASENA_INCORRECTA"), 
                            JOptionPane.ERROR_MESSAGE);
                    break;
                case 6:
                    JOptionPane.showMessageDialog(this,
                            ResourceBundle.getBundle("messages.messages").getString("NO_DIGITO"),
                            ResourceBundle.getBundle("messages.messages").getString("CONTRASENA_INCORRECTA"), 
                            JOptionPane.ERROR_MESSAGE);
                    break;
                default:
                    JOptionPane.showMessageDialog(this,
                            ResourceBundle.getBundle("messages.messages").getString("ERROR_DESCONOCIDO"),
                            ResourceBundle.getBundle("messages.messages").getString("CONTRASENA_INCORRECTA"), 
                            JOptionPane.ERROR_MESSAGE);
                    break;
            }
        } else {            
            JOptionPane.showMessageDialog(this,
                    ResourceBundle.getBundle("messages.messages").getString("CONTRASENA_INCORRECTA"),
                    ResourceBundle.getBundle("messages.messages").getString("CONTRASENA_INCORRECTA"), 
                    JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NuevaContrasena().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblAnterior;
    private javax.swing.JLabel lblNueva;
    private javax.swing.JLabel lblRepite;
    private javax.swing.JPasswordField txtAnterior;
    private javax.swing.JPasswordField txtNueva;
    private javax.swing.JPasswordField txtRepite;
    // End of variables declaration//GEN-END:variables


    private void javaHelp() {
        try {
            File fichero = new File(Configuration.getJavaHelp());
            URL hsURL = fichero.toURI().toURL();            
            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            
            HelpBroker hb = helpset.createHelpBroker();
            hb.enableHelpKey(this.getContentPane(), "principal", helpset);

            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();            
            Point p = new Point((int)screenSize.getWidth()/4,(int)screenSize.getHeight()/4);
            hb.setLocation(p);
        } catch (MalformedURLException ex) {
            source.Logger.error("NuevaContrasena", "javaHelp()", "URL mal formada", ex.getMessage());
        } catch (HelpSetException ex) {
            source.Logger.error("NuevaContrasena", "javaHelp()", "Excepcion general", ex.getMessage());
        }
    }
}
