/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.HelpSetException;
import javax.swing.JOptionPane;
import source.Configuration;
import source.InstanceManager;
import source.TableManager;

/**
 *
 * @author Andres LLamosas
 */
public class Opciones extends javax.swing.JDialog {

    TableManager tm;
    public boolean cambios = false;

    /**
     * Creates new form Opciones
     */
    public Opciones() {
        initComponents();
        getRootPane().setDefaultButton(this.btnAceptar);
        javaHelp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCambiarContrasena = new javax.swing.JButton();
        btnNotificaciones = new javax.swing.JButton();
        btnAjustesAvanzados = new javax.swing.JButton();
        btnCambiarTema = new javax.swing.JButton();
        btnCambiarIdioma = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setTitle(ResourceBundle.getBundle("messages.messages").getString("OPCIONES"));
        setMinimumSize(new java.awt.Dimension(230, 280));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(230, 280));
        setResizable(false);
        setSize(new java.awt.Dimension(230, 280));

        btnCambiarContrasena.setText(ResourceBundle.getBundle("messages.messages").getString("CAMBIAR_CONTRASENA"));
        btnCambiarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarContrasenaActionPerformed(evt);
            }
        });

        btnNotificaciones.setText(ResourceBundle.getBundle("messages.messages").getString("NOTIFICACIONES"));
        btnNotificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificacionesActionPerformed(evt);
            }
        });

        btnAjustesAvanzados.setText(ResourceBundle.getBundle("messages.messages").getString("AJUSTES_AVANZADOS"));
        btnAjustesAvanzados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjustesAvanzadosActionPerformed(evt);
            }
        });

        btnCambiarTema.setText(ResourceBundle.getBundle("messages.messages").getString("TEMAS"));
        btnCambiarTema.setToolTipText(ResourceBundle.getBundle("messages.messages").getString("TEMAS"));
        btnCambiarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarTemaActionPerformed(evt);
            }
        });

        btnCambiarIdioma.setText(ResourceBundle.getBundle("messages.messages").getString("IDIOMA"));
        btnCambiarIdioma.setAlignmentY(0.0F);
        btnCambiarIdioma.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnCambiarIdioma.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnCambiarIdioma.setIconTextGap(20);
        btnCambiarIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarIdiomaActionPerformed(evt);
            }
        });

        btnAceptar.setText(ResourceBundle.getBundle("messages.messages").getString("ACEPTAR"));
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCambiarContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(btnCambiarIdioma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCambiarTema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNotificaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAjustesAvanzados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCambiarContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btnCambiarIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCambiarTema, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAjustesAvanzados, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAceptar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarContrasenaActionPerformed
        NuevaContrasena cambiarContrasena = new NuevaContrasena(tm);
        cambiarContrasena.setVisible(true);
    }//GEN-LAST:event_btnCambiarContrasenaActionPerformed

    private void btnCambiarIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarIdiomaActionPerformed
        Idiomas cambiarIdioma = new Idiomas(this);
        cambiarIdioma.setVisible(true);
    }//GEN-LAST:event_btnCambiarIdiomaActionPerformed

    private void btnCambiarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarTemaActionPerformed
        Temas cambiarTema = new Temas(this);
        cambiarTema.setVisible(true);
    }//GEN-LAST:event_btnCambiarTemaActionPerformed

    private void btnNotificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificacionesActionPerformed
        Notificaciones notificaciones = new Notificaciones(this);
        notificaciones.setVisible(true);
    }//GEN-LAST:event_btnNotificacionesActionPerformed

    private void btnAjustesAvanzadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjustesAvanzadosActionPerformed
        AjustesAvanzados avanzados = new AjustesAvanzados();
        avanzados.setVisible(true);
    }//GEN-LAST:event_btnAjustesAvanzadosActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        Login.reiniciarServidor();
        if (cambios) {
            reiniciar();
        }
        this.setVisible(false);
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Opciones().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAjustesAvanzados;
    private javax.swing.JButton btnCambiarContrasena;
    private javax.swing.JButton btnCambiarIdioma;
    private javax.swing.JButton btnCambiarTema;
    private javax.swing.JButton btnNotificaciones;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void reiniciar() {
        Locale.setDefault(new Locale(Configuration.getPropIdioma()));
        JOptionPane.showMessageDialog(this,
                ResourceBundle.getBundle("messages.messages").getString("REINICIAR"),
                ResourceBundle.getBundle("messages.messages").getString("NERON"), 
                JOptionPane.INFORMATION_MESSAGE);
        try {
            InstanceManager.finalizarInstance();
            Process proc = Runtime.getRuntime().exec("Neron.exe");
            proc.waitFor();
            new InstanceManager().cerrarApp();
        } catch (IOException ex) {
            source.Logger.error("Opciones", "reiniciar()", 
                    "Excepción general", ex.getMessage());
        } catch (InterruptedException ex) {
            source.Logger.error("Opciones", "reiniciar()", 
                    "Proceso interrumpido", ex.getMessage());
        }
    }

    public void setTableManager(TableManager tm) {
        this.tm = tm;
    }

    private void javaHelp() {
        try {
            File fichero = new File(Configuration.getJavaHelp());
            URL hsURL = fichero.toURI().toURL();            
            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            
            HelpBroker hb = helpset.createHelpBroker();
            hb.enableHelpKey(this.getContentPane(), "principal", helpset);

            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();            
            Point p = new Point((int)screenSize.getWidth()/4,(int)screenSize.getHeight()/4);
            hb.setLocation(p);
        } catch (MalformedURLException ex) {
            source.Logger.error("Opciones", "javaHelp()", 
                    "URL mal formada", ex.getMessage());
        } catch (HelpSetException ex) {
            source.Logger.error("Opciones", "javaHelp()", 
                    "Excepcion general", ex.getMessage());
        }
    }
}
