/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import source.Configuration;
import source.PassManager;

/**
 *
 * @author Andres
 */
public class PrimerInicio extends javax.swing.JDialog {

    /**
     * Creates new form EstablecerContrasena
     */
    public PrimerInicio() {
        Configuration.crearProperties();
        Configuration.crearPropIdioma(Locale.getDefault().toString());
        seleccionarIdioma();
        initComponents();
        this.ayuda.setIcon(new ImageIcon("media/ayuda.png"));
        this.getRootPane().setDefaultButton(this.entrar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtPassRep = new javax.swing.JPasswordField();
        ayuda = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        entrar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(ResourceBundle.getBundle("messages.messages").getString("NUEVA_CONTRASENA"));
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(0, 0, 200, 174));
        setFont(new java.awt.Font("Arial Unicode MS", 0, 10)); // NOI18N
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setResizable(false);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        txtPass.setToolTipText(ResourceBundle.getBundle("messages.messages").getString("SEGURIDAD_MINIMA"));

        jLabel3.setText(ResourceBundle.getBundle("messages.messages").getString("REPITE_CONTRASENA"));

        txtPassRep.setToolTipText(ResourceBundle.getBundle("messages.messages").getString("SEGURIDAD_MINIMA"));

        ayuda.setIcon(new ImageIcon("media/ayuda.png"));
        ayuda.setToolTipText(ResourceBundle.getBundle("messages.messages").getString("SEGURIDAD_MINIMA"));

        jLabel2.setText(ResourceBundle.getBundle("messages.messages").getString("NUEVA_CONTRASENA"));

        entrar.setText(ResourceBundle.getBundle("messages.messages").getString("ACEPTAR"));
        entrar.setFocusable(false);
        entrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        entrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(entrar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(entrar)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPass)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPassRep))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel1.setText(ResourceBundle.getBundle("messages.messages").getString("PRIMER_INICIO"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        this.requestFocus(false);
    }//GEN-LAST:event_formFocusLost

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        PassManager pm = new PassManager();
        switch (pm.validarComplejidad(this.txtPass, this.txtPassRep)) {
            case -1:
                JOptionPane.showMessageDialog(this,
                        ResourceBundle.getBundle("messages.messages")
                                .getString("NO_COINCIDEN"),
                        ResourceBundle.getBundle("messages.messages")
                                .getString("CONTRASENA_INCORRECTA"),
                        JOptionPane.ERROR_MESSAGE);
                break;
            case 0:
                pm.establecerContrasena(txtPass);
                this.setVisible(false);
                break;
            case 1:
                JOptionPane.showMessageDialog(this,
                        ResourceBundle.getBundle("messages.messages")
                                .getString("DEMASIADO_CORTA"),
                        ResourceBundle.getBundle("messages.messages")
                                .getString("CONTRASENA_INCORRECTA"), 
                        JOptionPane.ERROR_MESSAGE);
                break;
            case 2:
                JOptionPane.showMessageDialog(this,
                        ResourceBundle.getBundle("messages.messages")
                                .getString("ESPACIOS_EN_BLANCO"),
                        ResourceBundle.getBundle("messages.messages")
                                .getString("CONTRASENA_INCORRECTA"), 
                        JOptionPane.ERROR_MESSAGE);
                break;
            case 3:
                JOptionPane.showMessageDialog(this,
                        ResourceBundle.getBundle("messages.messages")
                                .getString("NO_CARACTER_ESPECIAL"),
                        ResourceBundle.getBundle("messages.messages")
                                .getString("CONTRASENA_INCORRECTA"),
                        JOptionPane.ERROR_MESSAGE);
                break;
            case 4:
                JOptionPane.showMessageDialog(this,
                        ResourceBundle.getBundle("messages.messages")
                                .getString("NO_MAYUSCULA"),
                        ResourceBundle.getBundle("messages.messages")
                                .getString("CONTRASENA_INCORRECTA"),
                        JOptionPane.ERROR_MESSAGE);
                break;
            case 5:
                JOptionPane.showMessageDialog(this,
                        ResourceBundle.getBundle("messages.messages")
                                .getString("NO_MINUSCULA"),
                        ResourceBundle.getBundle("messages.messages")
                                .getString("CONTRASENA_INCORRECTA"), 
                        JOptionPane.ERROR_MESSAGE);
                break;
            case 6:
                JOptionPane.showMessageDialog(this,
                        ResourceBundle.getBundle("messages.messages")
                                .getString("NO_DIGITO"),
                        ResourceBundle.getBundle("messages.messages")
                                .getString("CONTRASENA_INCORRECTA"), 
                        JOptionPane.ERROR_MESSAGE);
                break;
            default:
                JOptionPane.showMessageDialog(this,
                        ResourceBundle.getBundle("messages.messages")
                                .getString("ERROR_DESCONOCIDO"),
                        ResourceBundle.getBundle("messages.messages")
                                .getString("CONTRASENA_INCORRECTA"), 
                        JOptionPane.ERROR_MESSAGE);
                break;
        }
    }//GEN-LAST:event_entrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimerInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimerInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimerInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimerInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PrimerInicio().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ayuda;
    private javax.swing.JButton entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPassRep;
    // End of variables declaration//GEN-END:variables

    private void seleccionarIdioma() {
        String[] idiomas = {
            "English",
            "Español",
            "Deustch",
            "中文",
            "Français",
            "русский",
            "Italiano",
            "Тоҷикистон",
            "Zulu"};

        String idioma = (String) JOptionPane.showInputDialog(this, "", 
                ResourceBundle.getBundle("messages.messages").getString("SELECCIONA_IDIOMA"),
                JOptionPane.QUESTION_MESSAGE, null, idiomas, idiomas[0]);
        if(idioma != null) {
            switch (idioma) {
                case "Español":
                    Configuration.crearPropIdioma("es");
                    Locale.setDefault(new Locale("es"));
                    break;
                case "English":
                    Configuration.crearPropIdioma("en");
                    Locale.setDefault(new Locale("en"));
                    break;
                case "Françoise":
                    Configuration.crearPropIdioma("fr");
                    Locale.setDefault(new Locale("fr"));
                    break;
                case "Deustch":
                    Configuration.crearPropIdioma("de");
                    Locale.setDefault(new Locale("de"));
                    break;
                case "русский":
                    Configuration.crearPropIdioma("ru");
                    Locale.setDefault(new Locale("ru"));
                    break;
                case "中文":
                    Configuration.crearPropIdioma("zh");
                    Locale.setDefault(new Locale("zh"));
                    break;
                case "Italiano":
                    Configuration.crearPropIdioma("it");
                    Locale.setDefault(new Locale("it"));
                    break;
                case "Тоҷикистон":
                    Configuration.crearPropIdioma("tg");
                    Locale.setDefault(new Locale("tg"));
                    break;
                case "Zulu":
                    Configuration.crearPropIdioma("zu");
                    Locale.setDefault(new Locale("zu"));
                    break;
            }
        }
    }
}
